# Processo seletivo Syngenta Digital - Desafio técnico - 04/2021
### Candidato: Daniel Valadares Piçarro.

In [1]:
import os
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib
import imageio

# Finding number of green pixels

Reading .bmp file

In [2]:
path = './desafio_pixel_syngenta_digital'
im = imageio.imread(os.path.join(path,'Syngenta.bmp'))
im.shape  # im is a numpy array

(300, 420, 4)

Counting number of green pixels and storing white cell's indices (to be used in the second part).

In [24]:
green_count = white_count = 0
white_x = []
white_y = []
blank_matrix = np.zeros((im.shape[0], im.shape[1]))

for pixel_length in range(im.shape[0]):
    for pixel_height in range(im.shape[1]):
        if im[pixel_length][pixel_height][0] == 96 and im[pixel_length][pixel_height][1] == 192:
            green_count += 1
        elif all(pixel == 255 for pixel in im[pixel_length][pixel_height]):
            white_x.append(pixel_length)
            white_y.append(pixel_height)
            blank_matrix[pixel_length][pixel_height] = 1
            white_count += 1
        
        
print(f"Answer: Number of green pixels: {green_count}\n\nNumber of white pixels: {white_count}")

Answer: Number of green pixels: 298

Number of white pixels: 466

# Finding hidden message

Checking whether there aren't any odd colored pixels (other than green, black and white).

In [25]:
black_pixels = 0
total_pixels_count = 0

for pixel_length in range(im.shape[0]):
    for pixel_height in range(im.shape[1]):
        if (im[pixel_length][pixel_height][0] == 0 and
            im[pixel_length][pixel_height][1] == 0 and
            im[pixel_length][pixel_height][2] == 0 and
            im[pixel_length][pixel_height][3] == 255):
            black_pixels += 1
        total_pixels_count += 1
    
print(f" black_pixels = {black_pixels}\n total = {total_pixels_count}\n dif = {total_pixels_count - (black_pixels + 298 + 466)}")

 black_pixels = 125236
 total = 126000
 dif = 0

Highlighting white cells

In [6]:
df = pd.DataFrame(blank_matrix)
chunk = df.iloc[min(white_x): max(white_x) + 1, min(white_y): max(white_y) + 1]
cm = sns.light_palette("green", as_cmap=True)
s = chunk.style.background_gradient(cmap=cm)
s

As shown above on the highlighted cells, the hidden message in the .bmp file is "Syngenta Digital Hire me".